src/main/java/org/mik/first/servlet/FormServlet.java
package org.mik.first.servlet;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/formServlet")
public class FormServlet extends HttpServlet {

    public FormServlet() {
        super();
    }

    @Override
    protected void doPost(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws ServletException, IOException {
        String yourName = httpServletRequest.getParameter("your_name");
        PrintWriter writer = httpServletResponse.getWriter();
        writer.println("<h1>Hello "+yourName+"</h1>");
        writer.close();
    }
}

src/main/java/org/mik/first/servlet/HelloWorldServlet.java
package org.mik.first.servlet;

import org.mik.first.Control;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

public class HelloWorldServlet extends HttpServlet {

    private Control control;

    public HelloWorldServlet() {
        this.control = new Control();
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        this.control.start();
        PrintWriter writer = resp.getWriter();

        writer.println("Done!");
    }
}

src/main/java/org/mik/first/servlet/IpServlet.java
package org.mik.first.servlet;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;

@WebServlet("/ip")
public class IpServlet extends HttpServlet {
}

src/main/java/org/mik/first/servlet/PersonServlet.java
package org.mik.first.servlet;

import org.mik.first.domain.Country;
import org.mik.first.domain.Person;
import org.mik.first.services.CountryService;
import org.mik.first.services.PersonService;

import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.Optional;
import java.util.stream.Stream;

public class PersonServlet extends HttpServlet {

    private PersonService personService;
    private CountryService countryService;

    public PersonServlet() {
        this.personService = PersonService.getInstance();
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.getSession();
        String name = Optional.ofNullable(req.getCookies())
                                .map(Stream::of)
                                .orElseGet(Stream::empty)
                                .filter(c->"name".equals(c.getName()))
                                .findFirst()
                                .map(Cookie::getValue)
                                .map(URLDecoder::decode)
                                .orElse(null);
        this.handle(resp, name);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            String name = req.getParameter("name");
            String address = req.getParameter("address");
            String personalId = req.getParameter("pId");
            String countryId = req.getParameter("cId");

            Country country = this.countryService.findById(countryId);
            if (country==null) {
                resp.sendRedirect("Error");
                return;
            }

            Person person = new Person(null, name, address, personalId, country);
            this.personService.pay(person);

            Cookie cookie = new Cookie("name", URLEncoder.encode(name, "UTF-8"));
            resp.addCookie(cookie);
            resp.sendRedirect("clientList");
        }
        catch (Exception e) {
            resp.sendRedirect("Error");
        }
    }

    private void handle(HttpServletResponse response, String name) throws IOException {
        PrintWriter writer = response.getWriter();
        writer.println("<html><head></head><body>");
        if (name!=null)
            writer.println("<h1>Hello " + name + "!</h1>");
        writer.println("<form method=\"POST\">");
        writer.println("Name: <input type=\"text\" name=\"name\" />");
        writer.println("Address: <input type=\"text\" name=\"address\" />");
        writer.println("Personal ID: <input type=\"text\" name=\"pId\" />");
        writer.println("Country id: <input type=\"text\" name=\"cId\" />");
        writer.println("<input type=\"submit\"/>");
        writer.println("</form>");
        writer.println("</body>");
        writer.println("</html>");
    }

    private void printHtmlHeader(PrintWriter writer) {
        writer.println("<html><head></head><body>");
    }

}

src/main/java/org/mik/first/servlet/db/AbstractDbServlet.java
package org.mik.first.servlet.db;

import org.mik.first.domain.AbstractEntity;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.List;

public class AbstractDbServlet<T extends AbstractEntity<Long>> extends HttpServlet {

    public static final String KEY_CURRENT_PAGE = "currentPage";
    public static final String KEY_RECORDS_PER_PAGE = "recordsPerPage";
    public static final String KEY_NUMBER_OF_PAGES = "numberOfPages";

    public static final String KEY_DATA = "data";

    public static final int DEF_RECORDS_PER_PAGES = 5;

    protected void setContentType(HttpServletResponse response) {
        response.setContentType("text/html;charset=UTF-8");
    }

    protected int extractIntRequestparam(HttpServletRequest request, String paramName, int defaultValue) {

        try {
            return Integer.parseInt(request.getParameter(paramName));
        }
        catch (Exception e) {
            return defaultValue;
        }
    }

    protected void setPagerData(HttpServletRequest request, List<T> data, long maxCounts, int recordsPerPage, int currentPage) {
        request.setAttribute(KEY_DATA, data);
        long numberOfPages = maxCounts / recordsPerPage;
        if (maxCounts % recordsPerPage > 0)
            ++numberOfPages;
        request.setAttribute(KEY_NUMBER_OF_PAGES, numberOfPages);
        request.setAttribute(KEY_CURRENT_PAGE, currentPage);
        request.setAttribute(KEY_RECORDS_PER_PAGE, recordsPerPage);

    }
}

src/main/java/org/mik/first/servlet/jsf/AbstractController.java
package org.mik.first.servlet.jsf;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.mik.first.domain.AbstractEntity;

import javax.faces.component.UICommand;
import javax.faces.event.ActionEvent;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public abstract class AbstractController<T extends AbstractEntity<Long>> implements Serializable {

    private static final Logger LOG  = LogManager.getLogger();
    private static final Boolean DEBUG_TEMPORARY = true;

    public static final int DEFAULT_ROWS_PER_PAGE = 5;
    public static final int DEFAULT_PAGE_RANGE = 10;

    private List<T> countryList;
    private long totalRows;
    private int rowsPerPage=DEFAULT_ROWS_PER_PAGE;
    private int totalPages;
    private int currentPage;
    private List<Integer> pages=new ArrayList<>();


    protected abstract List<T> findAll(int currentPage, int rowsPerPage) throws Exception;

    protected abstract long getCounts() throws Exception;

    public List<T> getDataList() throws Exception {
        if (this.countryList == null)
            loadDataList();
        return this.countryList;
    }

    public void setDataList(List<T> list) {
        this.countryList = list;
    }

    public long getTotalRows() {
        return totalRows;
    }

    public int getRowsPerPage() {
        return rowsPerPage;
    }

    public void setRowsPerPage(int rowsPerPage) {
        if (rowsPerPage<totalRows)
            this.rowsPerPage = rowsPerPage;
    }

    public long getTotalPages() {
        return totalPages;
    }

    public long getCurrentPage() {
        return currentPage;
    }

    public void page(int page) {
        if (page<0 && page >= totalPages)
            return;
        currentPage = page;
        loadDataList();
    }

    public List<Integer> getPages() {
        return pages;
    }

    private void loadDataList() {
        try {
            this.countryList = findAll(this.currentPage, this.rowsPerPage);
            this.totalRows = getCounts();
            this.totalPages = Long.valueOf(totalRows % this.rowsPerPage == 0 ? totalRows / rowsPerPage : totalRows/rowsPerPage + 1).intValue();
            this.pages.clear();
            for(int i=0;i<totalPages;++i)
                pages.add(i);
        }
        catch (Exception e) {
            LOG.error(e);
        }
    }

    public void page(ActionEvent event) {
        page(((Integer) ((UICommand) event.getComponent()).getValue()));
    }

    public void pageFirst() {
        page(0);
    }

    public void pageNext() {
        if (currentPage<totalPages)
            page(currentPage+1);
    }

    public void pagePrev() {
        if (currentPage>0)
            page(currentPage-1);
    }

    public void pageLast() {
        page(totalPages-1);
    }

    public String toUrl(String url, boolean redirect) {
        return String.format("/%s?faces-redirect=%s", url, redirect?"true":"false");
    }
}

src/main/java/org/mik/first/servlet/jsf/CountryController.java
package org.mik.first.servlet.jsf;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.mik.first.domain.Country;
import org.mik.first.services.CountryService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.util.List;
import java.util.Map;

@SessionScoped
@ManagedBean
public class CountryController extends AbstractController<Country> {

    private final static Logger LOG  = LogManager.getLogger();
    private final static Boolean DEBUG_TEMPORARY = true;


    private CountryService countryService;
    private String name;
    private String sign;

    public CountryController() {
        this.countryService = CountryService.getInstance();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    @Override
    protected List<Country> findAll(int currentPage, int rowsPerPage) throws Exception{
        return this.countryService.findAll(currentPage, rowsPerPage);
    }

    @Override
    protected long getCounts() throws Exception {
        return this.countryService.getCounts();
    }

    public String delete(long id) {
        try {
            this.countryService.delete(id);
            return toUrl("countries.xhtml",true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    public String update(long id) {
        try {
            Country c=this.countryService.findById(id);
            if (c==null)
                return null;
            Map<String, Object> sessionMapObject = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
            sessionMapObject.put("editRecord", c);
            return toUrl("api/editcountry.xhtml",true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    public String save(Country country) {
        try {
            this.countryService.save(country);
            return toUrl("countries.xhtml", true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    public String save(CountryController countryController) {
        try {
            Country country = new Country(countryController.name, countryController.sign);
            this.countryService.save(country);
            return toUrl("countries.xhtml", true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    public String updateCountry(Country country) {
        try {
            this.countryService.update(country);
            return toUrl("countries.xhtml", true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }
}

src/main/java/org/mik/first/servlet/jsf/NavigationController.java
package org.mik.first.servlet.jsf;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.security.Principal;

@ManagedBean(name = "navigationController", eager = true)
@RequestScoped
public class NavigationController implements Serializable {
    private static final long serialVersionUID = 1L;
    @ManagedProperty(value = "#{param.pageId}")
    private String pageId;

    public String moveToPage1() {
        return "countries";
    }

    public String moveToPage2() {
        return "page2";
    }

    public String moveToHomePage() {
        return "home";
    }

    public String processPage1() {
        return "page";
    }

    public String processPage2() {
        return "page";
    }

    public String showPage() {
        if(pageId == null)
            return "home";

        if(pageId.equals("1"))
            return "countries";

        if(pageId.equals("2"))
            return "persons";

        if (pageId.equals("99")) {
            logout();
            return "/home?faces-redirect=true";
        }
        return "home";
    }

    public String getPageId() {
        return pageId;
    }

    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    private void logout() {
        FacesContext facesContext =FacesContext.getCurrentInstance();
        facesContext.getExternalContext().invalidateSession();

    }

    public boolean isLogoutRendered() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        Principal p=request.getUserPrincipal();
        return p!=null;
    }

}

src/main/java/org/mik/first/servlet/jsf/PersonController.java
package org.mik.first.servlet.jsf;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.mik.first.domain.Country;
import org.mik.first.domain.Person;
import org.mik.first.services.CountryService;
import org.mik.first.services.PersonService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.util.Collections;
import java.util.List;
import java.util.Map;

@SessionScoped
@ManagedBean
public class PersonController extends AbstractController<Person> {

    private static final Logger LOG  = LogManager.getLogger();
    private static final Boolean DEBUG_TEMPORARY = false;

    private PersonService personService=PersonService.getInstance();
    private CountryService countryService = CountryService.getInstance();

    private String name;
    private String address;
    private Long countryId;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Long getCountryId() {
        return countryId;
    }

    public void setCountryId(Long country) {
        this.countryId = country;
    }

    public List<Country> getCountries() {
        try {
            return this.countryService.findAll();
        }
        catch (Exception e) {
            LOG.error(e);
            return Collections.EMPTY_LIST;
        }
    }

    public String update(Long id) {
        try {
             Person p = this.personService.findById(id);
             if (p==null)
                 return null;

            Map<String, Object> sessionMapObject = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
            sessionMapObject.put("editRecord", p);
            return toUrl("editperson.xhtml",true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    public String updatePerson(Person p) {
        try {
            Country c = this.countryService.findById(this.countryId);
            p.setCountry(c);
            this.personService.update(p);
            return toUrl("persons", true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }

    @Override
    protected List<Person> findAll(int currentPage, int rowsPerPage) throws Exception {
        return personService.findAll();
    }

    @Override
    protected long getCounts() throws Exception {
        return personService.getCounts();
    }

    public String delete(long id) {
        try {
            this.personService.delete(id);
            return toUrl("persons.xhtml", true);
        }
        catch (Exception e) {
            LOG.error(e);
            return null;
        }
    }
}

src/main/webapp/countries.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://java.sun.com/jsf/html">

<h:head>
    <title>List of Countries</title>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <h:outputStylesheet library="css" name="bootstrap.min.css"/>
    <title>JSF CRUD Example</title>
    <style type="text/css">
        .tableUpdated {
            width: 90% !important;
            margin: 17px 58px 0 !important;
        }

        .btnSpace {
            margin: 17px;
        }
    </style>
</h:head>

<h:body>
    <h:outputStylesheet library="css" name="style.css"/>
    <p class="text-center"><h2><h:outputText value="List of countries"/></h2></p>
    <h:form id="form" prependId="false">
        <h:commandButton action="home?faces-redirect = true" value="Back To Home Page" styleClass="btn btn-success btnSpace"/>
        <h:dataTable value="#{countryController.dataList}" var="country"
                     rendered="#{countryController.dataList ne null}"
                     class="table table-striped table-hover table-bordered tableUpdated"
                     rowClasses="odd,even">
            <h:column headerClass="first">
                <f:facet name="header">
                    Country ID
                </f:facet>
                <h:outputText value="#{country.id}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Country Name
                </f:facet>
                <h:outputText value="#{country.name}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Country sign
                </f:facet>
                <h:outputText value="#{country.sign}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Update
                </f:facet>
                <h:commandButton action="#{countryController.update(country.id)}" value="Update" styleClass="btn btn-primary"/>
            </h:column>
            <h:column headerClass="last">
                <f:facet name="header">Delete</f:facet>
                <h:commandButton action="#{countryController.delete(country.id)}" value="Delete" styleClass="btn btn-danger"/>
            </h:column>
        </h:dataTable>
        <div class="pager">
            <h:commandButton value="first" action="#{countryController.pageFirst}"
                             disabled="#{countryController.currentPage==0}" styleClass="btn btn-success btnSpace"/>
            <h:commandButton value="prev" action="#{countryController.pagePrev}"
                             disabled="#{countryController.currentPage==0}" styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <h:commandButton value="next" action="#{countryController.pageNext}"
                             disabled="#{countryController.currentPage eq countryController.totalPages-1}"
                             styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <h:commandButton value="last" action="#{countryController.pageLast}"
                             disabled="#{countryController.currentPage eq countryController.totalPages-1}"
                             styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <br/>
            <h:outputText value="Page #{countryController.currentPage+1} / #{countryController.totalPages}"/>
            <br/>

            <ui:repeat value="#{countryController.pages}" var="p">
                <h:commandLink value="#{p}" actionListener="#{countryController.page}"
                               rendered="${p != countryController.currentPage}"/>
                <h:outputText value="&lt;b&gt;#{p}&lt;/b&gt;" escape="false"
                              rendered="#{p == countryController.currentPage}"/>
                <h:outputText value="&nbsp;" escape="false"/>
            </ui:repeat>

            <br/>
            <h:outputLabel for="rowsPerPage" value="Rows per page"/>
            <h:inputText id="rowsPerPage" value="#{countryController.rowsPerPage}" size="3" maxlength="3"/>
            <h:commandButton value="Set" actionListener="#{countryController.pageFirst}" styleClass="btn btn-success btnSpace"/>
            <h:message for="rowsPerPage" errorStyle="color:red"/>
        </div>
        <div>
            <h:commandButton action="createcountry.xhtml?faces-redirect=true" value="Create New Country"
                             class="btn btn-success btnSpace"/>
        </div>
    </h:form>
</h:body>

</html>

src/main/webapp/error404.jsp
<%--
  Created by IntelliJ IDEA.
  User: zamek
  Date: 5/3/20
  Time: 11:44 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>404 Error - Page not found</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css"/>
</head>
<body>
    <div>
        <h1>Sorry the page you requested were not found</h1>
    </div>
</body>
</html>

src/main/webapp/error500.jsp
<%--
  Created by IntelliJ IDEA.
  User: zamek
  Date: 5/3/20
  Time: 11:44 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>500 Error - Server error</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css"/>
</head>
<body>
<div>
    <h1>Sorry, server error</h1>
</div>
</body>
</html>

src/main/webapp/exception.jsp
<%--
  Created by IntelliJ IDEA.
  User: zamek
  Date: 5/3/20
  Time: 11:44 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Error - Exception</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css"/>
</head>
<body>
<div>
    <h1>Sorry, something went wrong, check server log</h1>
</div>
</body>
</html>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <f:facet name="first">
        <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
        <title>Main menu</title>
    </f:facet>
    <h:outputStylesheet library="css" name="style.css"/>
</h:head>
<h:body>
    <h2>First Maven application</h2>
    <hr/>
    <h:form>
        <h:commandLink action="#{navigationController.showPage}"
                       styleClass="menu-item"
                       value="Home">
            <f:param name="pageId" value="3"/>
        </h:commandLink>

        <h:commandLink action="#{navigationController.showPage}"
                       styleClass="menu-item"
                       value="countries">
            <f:param name="pageId" value="1"/>
        </h:commandLink>


        <h:commandLink action="#{navigationController.showPage}"
                       styleClass="menu-item"
                       value="persons">
            <f:param name="pageId" value="2"/>
        </h:commandLink>

        <h:commandLink action="#{navigationController.showPage}"
                       styleClass="menu-item"
                       value="Logout"
                       rendered="#{navigationController.logoutRendered}">
            <f:param name="pageId" value="99"/>
        </h:commandLink>

    </h:form>
    <br/>
</h:body>

</html>

src/main/webapp/menuLeft.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <div>
        <ui:include src="countries.xhtml"/>
        <ui:include src="persons.xhtml"/>
<!--        <ui:include src="companies.xhtml"/>-->
    </div>
</ui:composition>

src/main/webapp/persons.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>List of Persons</title>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1" http-equiv="X-UA-Conpatible"/>
    <h:outputStylesheet library="css" name="bootstrap.min.css"/>
    <title>List of persons</title>
    <style type="text/css">
        .tableUpdated {
            width: 90% !important;
            margin: 17px 58px 0 !important;
        }
        .btnSpace {
            margin: 17px;
        }
    </style>
</h:head>
<h:body>
    <p class="text-center"><h2><h:outputText value="List of persons"/></h2></p>
    <h:form id="form" prependId="false">
        <h:commandButton action="home?faces-redirect = true" value="Back To Home Page" styleClass="btn btn-success btnSpace"/>
        <h:dataTable value="#{personController.dataList}" var="person"
                     rendered="#{personController.dataList ne null}"
                     class="table table-striped table-hover table-bordered tableUpdated"
                     rowClasses="odd,even">
            <h:column headerClass="first">
                <f:facet name="header">
                    person ID
                </f:facet>
                <h:outputText value="#{person.id}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Name
                </f:facet>
                <h:outputText value="#{person.name}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Address
                </f:facet>
                <h:outputText value="#{person.address}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Country
                </f:facet>
                <h:outputText value="#{person.country.name}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    Update
                </f:facet>
                <h:commandButton action="#{personController.update(person.id)}" value="Update" styleClass="btn btn-primary"/>
            </h:column>
            <h:column headerClass="last">
                <f:facet name="header">Delete</f:facet>
                <h:commandButton action="#{personController.delete(person.id)}" value="Delete" styleClass="btn btn-danger"/>
            </h:column>
        </h:dataTable>
        <div class="pager">
            <h:commandButton value="first" action="#{personController.pageFirst}"
                             disabled="#{personController.currentPage==0}" styleClass="btn btn-success btnSpace"/>
            <h:commandButton value="prev" action="#{personController.pagePrev}"
                             disabled="#{personController.currentPage==0}" styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <h:commandButton value="next" action="#{personController.pageNext}"
                             disabled="#{personController.currentPage eq personController.totalPages-1}"
                             styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <h:commandButton value="last" action="#{personController.pageLast}"
                             disabled="#{personController.currentPage eq personController.totalPages-1}"
                             styleClass="btn btn-success btnSpace"/>
            <h:outputText value="&nbsp;" escape="false"/>
            <br/>
            <h:outputText value="Page #{personController.currentPage+1} / #{personController.totalPages}"/>
            <br/>

            <ui:repeat value="#{personController.pages}" var="p">
                <h:commandLink value="#{p}" actionListener="#{personController.page}"
                               rendered="${p != personController.currentPage}"/>
                <h:outputText value="&lt;b&gt;#{p}&lt;/b&gt;" escape="false"
                              rendered="#{p == personController.currentPage}"/>
                <h:outputText value="&nbsp;" escape="false"/>
            </ui:repeat>

            <br/>
            <h:outputLabel for="rowsPerPage" value="Rows per page"/>
            <h:inputText id="rowsPerPage" value="#{personController.rowsPerPage}" size="3" maxlength="3"/>
            <h:commandButton value="Set" actionListener="#{personController.pageFirst}" styleClass="btn btn-success btnSpace"/>
            <h:message for="rowsPerPage" errorStyle="color:red"/>
        </div>
        <div>
            <h:commandButton action="createperson.xhtml?faces-redirect=true" value="Create New Person"
                             class="btn btn-success btnSpace"/>
        </div>
    </h:form>

</h:body>
</html>